### ISSUE TITLE
Unify "log" and "show"

### ISSUE THREAD

**Issue by vitalybe** [Nukesor/pueue#45]
I feel it'd be much more useful if `log` and `show` were unified and showed by default the latest log, of either running or finished jobs.

**Comment by Nukesor** [comment]
Shouldn't be too hard either. Probably only a few lines of code.

**Comment by Nukesor** [comment]
I'll look into this in the next few days. It's on my todo list now!

**Comment by Nukesor** [comment]
Ok. Here's what I've done.
I added a new flag to the `log` command, namely `keys` (`-k`). The default is the last finished process.
If you want to few other logs you need to specify them with `-k`.

`show` now shows the latest started process by default.

While I was at it, I refactored those two functions and they should be __significantly__ faster, since no socket communication will be used any longer.

**Comment by vitalybe** [comment]
Awesome! I'll check it out

**Comment by Nukesor** [comment]
I just released a new patch version with the new behavior on pypi :)

**Comment by sourcefrog** [comment]
It looks like in the Rust version they're now different again? It's a bit odd, as a new user, that it insists on using a different command to do the same thing, depending whether the task finished or not.

**Comment by Nukesor** [comment]
This ticket was about unifying the usage of the commands, not about unifying both commands into one.

It has been built like this, because the logic behind those two commands are completely different and the output of both commands is different.

`log` is more verbose and has more information that's unknown during runtime. On top of that, log is capable of investigating logs of multiple outputs at the same time (or only a subset of those)

With `show` you ONLY look at the output of a single command. And you can decide to follow the command.

Those are two different use cases, which already have a few flags for configuration.
IMO Combining both of these would be even more confusing in the long run.

**Comment by sourcefrog** [comment]
I guess I find it confusing that 

1. `log` can't say anything about a still-running command. Although there's no finish time or exit code, you do know the command, start time, cwd, and you have some output.

2. `log` sometimes(?) on a still-running or queued command produces no output and no error.

3. `show` can't show the stdout/stderr for a finished command. You do still have this text in memory.
